In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
# pd.set_option('display.expand_frame_repr', True)
# pd.set_option('display.width', 80)
phones_df = pd.read_csv('datasets/integrated_phones/phones.csv')

In [3]:
len(phones_df)

18424

In [4]:
phones_df.drop_duplicates(inplace=True)

In [5]:
len(phones_df)

7806

In [6]:
phones_len = len(phones_df)
phones_len

7806

In [7]:
null_features = phones_df.isna().sum().sort_values(ascending=False)
# null_features

# for i in null_features[null_features == phones_len].index:
#     print(i)
# null_features

features = ['location','rating','sold','candidate_model','device_type','aspect_ratio', 
     'price_old', 'price_savings','price_official', 'price_unofficial','price_updated',
     'price_variants','ruggedness','ip_rating','user_interface', 'fabrication', 
     'status','image_url','brightness', 'colors', 'scraped_at', 'detail_url', 'model']

for k, v in null_features.items():
    # print(k)
    if k in features:
        print(k, v)

price_savings 7042
price_old 7042
price_unofficial 5445
ruggedness 5090
ip_rating 5039
brightness 3390
location 2375
rating 1910
sold 1910
price_official 1899
user_interface 1174
aspect_ratio 758
fabrication 201
colors 3
status 3
model 0
candidate_model 0
device_type 0
detail_url 0
image_url 0
price_variants 0
price_updated 0
scraped_at 0

In [8]:
phones_df.drop(columns=null_features[null_features == phones_len].index.union(
    ['location','rating','sold','candidate_model','device_type','aspect_ratio', 
     'price_old', 'price_savings','price_official', 'price_unofficial','price_updated',
     'price_variants','ruggedness','ip_rating','user_interface', 'fabrication', 
     'status','image_url','brightness', 'colors', 'scraped_at', 'detail_url', 'model'
    ]), inplace=True)

In [9]:
phones_df['volte'].value_counts()

volte
Yes      7579
VoLTE     105
Name: count, dtype: int64

In [10]:
phones_df.isna().sum().sort_values(ascending=False )

waterproof                   4623
expandable_memory            2603
usb_type_c                   2350
ram_type                     1688
storage_type                 1585
quick_charging               1248
refresh_rate                 1122
face_unlock                   660
weight                        539
usb_otg                       500
notch                         228
screen_protection             222
sim_size                      195
width                         187
height                        187
thickness                     158
screen_to_body_ratio          154
volte                         122
audio_jack                     91
architecture                   87
speed                          71
video                          70
gpu                            63
usb                            16
gprs                           16
pixel_density                  16
features                       15
touch_screen                   12
sim_slot                       12
bluetooth                       8
cpu_cores                       3
wlan                            3
cpu                             2
gps                             2
chipset                         2
ram                             2
edge                            0
battery_capacity                0
display_type                    0
title                           0
brand                           0
price                           0
release_date                    0
screen_size                     0
resolution                      0
primary_camera_resolution       0
internal_storage                0
network                         0
loudspeaker                     0
operating_system                0
os_version                      0
dtype: int64

In [11]:
import numpy as np


phones_df.fillna({"waterproof":"No", "usb_type_c":"No", "ram_type":"Undefined", "storage_type":"Undefined", "quick_charging":"No","face_unlock":"No", "usb_otg": "No", "refresh_rate":"60 Hz", "screen_protection":"Undefined", "notch":"No", "audio_jack": "No", "expandable_memory": "No"}, inplace=True)

phones_df.loc[phones_df['bluetooth'] == 'Yes', 'bluetooth'] = "v5.0"
phones_df.loc[phones_df['volte'] == 'VoLTE', 'volte'] = "Yes"
phones_df.loc[phones_df['release_date'].str.lower() == 'not announced yet', 'release_date'] = np.nan
phones_df.loc[phones_df['release_date'].str.lower().str.contains('bangladesh'), 'release_date'] = phones_df['release_date'].str.replace('(Bangladesh)','')

phones_df['price'] = phones_df['price'].str.replace('Rp','').str.replace('.','').astype(float)
phones_df['os_version'] = phones_df['os_version'].str.replace('v','')
phones_df['audio_jack'] = phones_df['audio_jack'].str.replace(' ','')
phones_df['release_date'] = phones_df['release_date'].str.replace('Exp. ','')

In [12]:
phones_df['bluetooth'].value_counts()

bluetooth
v5.0                    4102
v4.2                     905
v5.2                     680
v5.3                     671
v5.4                     645
v5.1                     363
v4.1                     116
v4.0                     106
v3                        69
v5                        57
5.2, A2DP, LE             40
5.0, A2DP, LE             21
v6.0                      11
5.1 or 5.3, A2DP, LE       8
v2.1                       4
Name: count, dtype: int64

In [13]:
phones_df[[
'thickness',
'screen_to_body_ratio',
'width',
'height',
'weight',
'price',
'battery_capacity',
'screen_size',
'cpu_cores',
'pixel_density',
'architecture',
'quick_charging',
'refresh_rate',
]].head(10)

,thickness,screen_to_body_ratio,width,height,weight,price,battery_capacity,screen_size,cpu_cores,pixel_density,architecture,quick_charging,refresh_rate
0,9.4 mm,84.24 %,68.1 mm,146.5 mm,172 grams,4850000.0,Li-Po 4300mAh,"5.92""1080x2400p",8 cores,446 ppi,64 bit,30W Quick Charging,144 Hz
1,9.4 mm,80.21 %,77.6 mm,170.9 mm,240 grams,2650000.0,Li-Po 6000mAh,"6.59""1080x2340p",8 Cores,391 ppi,64 bit,Fast charging 30W,120 Hz
2,10.3 mm,82.07 %,77 mm,173 mm,239 grams,3720000.0,Li-Po 6000mAh,6.78''1080x2448p,8 Cores,395 ppi,64 bit,"Hyper, 65W: 100 % in 42 minutes",165 Hz
3,9.1 mm,84.24 %,68.1 mm,146.5 mm,169 grams,4500000.0,Li-Po 4300mAh,5.9''1080x2400p,8 Cores,446 ppi,64 bit,"Fast, 30W: 50 % in 30 minutes",120 Hz
4,10.3 mm,82.07 %,77 mm,173 mm,239 grams,6300000.0,Li-Po 6000mAh,6.78''1080x2448p,8 Cores,395 ppi,64 bit,"Hyper, 65W: 100 % in 42 minutes",165 Hz
5,8.9 mm,88.2%,76.8 mm,163.8 mm,225 grams,7990000.0,Li-Po 5500mAh,6.78''1080x2400p,8 Cores,388 ppi,64 bit,"65W wired, PD3.0, PPS, QC5, 100% in 46 min",165 Hz
6,8.9 mm,88.2%,76.8 mm,163.8 mm,225 grams,7875000.0,Li-Po 5500mAh,6.78''1080x2400p,8 Cores,388 ppi,64 bit,"65W wired, PD3.0, PPS, QC5, 100% in 46 min",165 Hz
7,9.4 mm,80.21 %,77.6 mm,170.9 mm,240 grams,2650000.0,Li-Po 6000mAh,"6.59""1080x2340p",8 Cores,391 ppi,64 bit,Fast charging 30W,120 Hz
8,10.3 mm,82.07 %,77 mm,173 mm,239 grams,4520000.0,Li-Po 6000mAh,6.78''1080x2448p,8 Cores,395 ppi,64 bit,"Hyper, 65W: 100 % in 42 minutes",165 Hz
9,9.9 mm,82.07 %,77.3 mm,172.8 mm,238 grams,3990000.0,Li-Po 6000mAh,6.78''1080x2448p,8 Cores,395 ppi,64 bit,"Fast, 65W: 70 % in 30 minutes",144 Hz

In [14]:
# phones_df.dropna(inplace=True)

In [15]:
phones_df['thickness'] = (phones_df['thickness'].str.extract(r"(\d+(?:\.\d+)?)").astype(float))
phones_df['screen_to_body_ratio'] = (phones_df['screen_to_body_ratio'].str.extract(r"(\d+(?:\.\d+)?)").astype(float))
phones_df['width'] = (phones_df['width'].str.extract(r"(\d+(?:\.\d+)?)").astype(float))
phones_df['height'] = (phones_df['height'].str.extract(r"(\d+(?:\.\d+)?)").astype(float))
phones_df['weight'] = (phones_df['weight'].str.extract(r"(\d+(?:\.\d+)?)").astype(float))

phones_df['weight'] = phones_df['weight'].fillna(
    phones_df['weight'].median()
)
phones_df['thickness'] = phones_df['thickness'].fillna(
    phones_df['thickness'].median()
)
phones_df['screen_to_body_ratio'] = phones_df['screen_to_body_ratio'].fillna(
    phones_df['screen_to_body_ratio'].median()
)
phones_df['width'] = phones_df['width'].fillna(
    phones_df['width'].median()
)
phones_df['height'] = phones_df['height'].fillna(
    phones_df['height'].median()
)

In [16]:
phones_df.dropna(inplace=True)
# phones_df.isna().sum().sort_values(ascending=False)

In [17]:

phones_df['quick_charging'] = phones_df['quick_charging'].str.extract(r"(\d+\s*W|No)")
phones_df['refresh_rate'] = phones_df['refresh_rate'].str.extract(r"(\d+)").astype(int)
phones_df['battery_capacity'] = phones_df['battery_capacity'].str.findall(r"(\d+)").str[0].astype(float)
phones_df['screen_size'] = phones_df['screen_size'].str.findall(r"(\d+\s*x\s*\d+)").str[0].astype(str)
phones_df['cpu_cores'] = phones_df['cpu_cores'].str.findall(r"(\d+)").str[0].astype(int)
phones_df['pixel_density'] = phones_df['pixel_density'].str.findall(r"(\d+)").str[0].astype(int)
phones_df['architecture'] = phones_df['architecture'].str.findall(r"(\d+)").str[0].astype(int)

In [18]:
phones_df[[
'thickness',
'screen_to_body_ratio',
'width',
'height',
'weight',
'price',
'battery_capacity',
'screen_size',
'cpu_cores',
'pixel_density',
'architecture',
'quick_charging',
'refresh_rate',
]].head(10)

,thickness,screen_to_body_ratio,width,height,weight,price,battery_capacity,screen_size,cpu_cores,pixel_density,architecture,quick_charging,refresh_rate
0,9.4,84.24,68.1,146.5,172.0,4850000.0,4300.0,1080x2400,8,446,64,30W,144
1,9.4,80.21,77.6,170.9,240.0,2650000.0,6000.0,1080x2340,8,391,64,30W,120
2,10.3,82.07,77.0,173.0,239.0,3720000.0,6000.0,1080x2448,8,395,64,65W,165
3,9.1,84.24,68.1,146.5,169.0,4500000.0,4300.0,1080x2400,8,446,64,30W,120
4,10.3,82.07,77.0,173.0,239.0,6300000.0,6000.0,1080x2448,8,395,64,65W,165
7,9.4,80.21,77.6,170.9,240.0,2650000.0,6000.0,1080x2340,8,391,64,30W,120
8,10.3,82.07,77.0,173.0,239.0,4520000.0,6000.0,1080x2448,8,395,64,65W,165
9,9.9,82.07,77.3,172.8,238.0,3990000.0,6000.0,1080x2448,8,395,64,65W,144
10,10.3,82.07,77.0,173.0,239.0,5500000.0,6000.0,1080x2448,8,395,64,65W,165
13,8.9,88.20,76.8,163.8,224.0,6050000.0,5500.0,1080x2400,8,388,64,65W,144

In [19]:
# phones_df['weight'] = phones_df['weight'].fillna(
#     phones_df['weight'].median()
# )
# phones_df['thickness'] = phones_df['thickness'].fillna(
#     phones_df['thickness'].median()
# )
# phones_df['screen_to_body_ratio'] = phones_df['screen_to_body_ratio'].fillna(
#     phones_df['screen_to_body_ratio'].median()
# )
# phones_df['width'] = phones_df['width'].fillna(
#     phones_df['width'].median()
# )
# phones_df['height'] = phones_df['height'].fillna(
#     phones_df['height'].median()
# )

In [20]:
phones_df.isna().sum().sort_values(ascending=False)

quick_charging               60
screen_size                  13
brand                         0
release_date                  0
architecture                  0
audio_jack                    0
battery_capacity              0
bluetooth                     0
chipset                       0
cpu                           0
cpu_cores                     0
display_type                  0
edge                          0
expandable_memory             0
face_unlock                   0
features                      0
gprs                          0
title                         0
price                         0
gpu                           0
gps                           0
height                        0
internal_storage              0
notch                         0
operating_system              0
loudspeaker                   0
network                       0
pixel_density                 0
os_version                    0
ram                           0
primary_camera_resolution     0
ram_type                      0
refresh_rate                  0
resolution                    0
screen_protection             0
screen_to_body_ratio          0
sim_size                      0
sim_slot                      0
speed                         0
storage_type                  0
thickness                     0
touch_screen                  0
usb                           0
usb_otg                       0
usb_type_c                    0
video                         0
volte                         0
waterproof                    0
weight                        0
width                         0
wlan                          0
dtype: int64

In [21]:
len(phones_df)

7091

In [22]:
phones_df.dropna(inplace=True)

In [23]:
len(phones_df)

7018

In [24]:
# len(phones_df[phones_df['release_date'] == 'Not announced yet']['release_date'])
phones_df['ram_type'] = phones_df['ram_type'].str.upper()

In [25]:
phones_df['battery_capacity'].value_counts()

battery_capacity
5000.0    2933
6000.0     504
4000.0     373
3765.0     313
4230.0     308
4500.0     284
3000.0     266
5200.0     236
5160.0     176
4300.0     133
5500.0     130
7000.0     104
3300.0      82
4600.0      65
4030.0      59
5100.0      56
6300.0      56
4100.0      47
5020.0      45
4020.0      43
3360.0      43
3500.0      41
6500.0      39
5030.0      39
3260.0      37
4380.0      32
5800.0      29
3200.0      29
3400.0      29
2900.0      29
5600.0      28
4610.0      28
3900.0      25
2600.0      23
3075.0      21
4200.0      20
5400.0      20
4050.0      19
3080.0      19
2500.0      18
4520.0      17
4045.0      14
4025.0      12
3180.0      11
4235.0      11
5110.0      11
3050.0      10
5630.0       9
4830.0       9
4805.0       8
4400.0       8
4850.0       8
5910.0       7
4315.0       7
3350.0       7
3070.0       7
4880.0       6
4780.0       6
3120.0       6
3700.0       5
4700.0       5
4900.0       5
3730.0       4
2000.0       4
4450.0       4
3100.0       4
4310.0       3
6100.0       3
5260.0       3
5410.0       3
3060.0       3
2630.0       2
4260.0       2
4800.0       2
2800.0       2
4720.0       2
4820.0       2
4065.0       1
2420.0       1
4015.0       1
1900.0       1
4810.0       1
Name: count, dtype: int64

In [26]:
string_columns = phones_df.select_dtypes(include=['object','string']).columns
string_columns

Index(['brand', 'title', 'release_date', 'audio_jack', 'bluetooth', 'chipset',
       'cpu', 'display_type', 'edge', 'expandable_memory', 'face_unlock',
       'features', 'gprs', 'gps', 'gpu', 'internal_storage', 'loudspeaker',
       'network', 'notch', 'operating_system', 'os_version',
       'primary_camera_resolution', 'quick_charging', 'ram', 'ram_type',
       'resolution', 'screen_protection', 'screen_size', 'sim_size',
       'sim_slot', 'speed', 'storage_type', 'touch_screen', 'usb', 'usb_otg',
       'usb_type_c', 'video', 'volte', 'waterproof', 'wlan'],
      dtype='str')

In [27]:
len(phones_df)

7018

In [28]:

phones_df.to_csv('datasets/cleaned_data/phones.csv', index=False)