In [1]:
import pandas as pd
# pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", None)
# pd.set_option('display.expand_frame_repr', True)
# pd.set_option('display.width', 80)
phones_df = pd.read_csv('datasets/cleaned_data/phones.csv')

In [2]:
len(phones_df)

7018

In [3]:
phones_df.columns

Index(['brand', 'title', 'price', 'release_date', 'architecture', 'audio_jack',
       'battery_capacity', 'bluetooth', 'chipset', 'cpu', 'cpu_cores',
       'display_type', 'edge', 'expandable_memory', 'face_unlock', 'features',
       'gprs', 'gps', 'gpu', 'height', 'internal_storage', 'loudspeaker',
       'network', 'notch', 'operating_system', 'os_version', 'pixel_density',
       'primary_camera_resolution', 'quick_charging', 'ram', 'ram_type',
       'refresh_rate', 'resolution', 'screen_protection', 'screen_size',
       'screen_to_body_ratio', 'sim_size', 'sim_slot', 'speed', 'storage_type',
       'thickness', 'touch_screen', 'usb', 'usb_otg', 'usb_type_c', 'video',
       'volte', 'waterproof', 'weight', 'width', 'wlan'],
      dtype='str')

In [4]:
import re

def extract_ram_storage(title):
    
    possible_formats = [
        r'(\d+)\s*gb(\d+)\s*gb',
        r'(\d+)gb\s*(\d+)gb\s*',
        r'(\d+)\s*/\s*(\d+)',
        r'(\d+)\s*/\s*(\d+)\s*gb',
        r'(\d+)\s*gb\s*/\s*(\d+)\s*gb',
        r'ram\s*(\d+)\s*(\d+)\s*gb',
        r'ram\s*(\d+)\s+rom\s*(\d+)\s*gb',
        r'ram\s*(\d+)\s*gb\s+rom\s*(\d+)\s*gb'
    ]
    
    if pd.isna(title):
        return pd.Series([None, None])
    
    title = title.lower()
    
    for format in possible_formats:
        match = re.search(format, title)

        if match:
            return pd.Series([match[1], match[2]])
    
    
    return pd.Series([None, None])

In [5]:
phones_df[['ram','internal_storage']] = phones_df['title'].apply(extract_ram_storage)

In [6]:
sample = phones_df.copy()

In [27]:
sample[sample['ram'].isna() & sample['title'].str.contains('gb')][['title','ram','internal_storage']].sample(10)

                                                  title  ram internal_storage
5967                  Vivo S1 4G ram 6gb internal 128gb  NaN              NaN
133         asus rog phone 6 256gb rom 8gb ram original  NaN              NaN
1987                    Oppo Reno 256gb Resmi Indonesia  NaN              NaN
6611                 Xiaomi Mi A1 Ram 4gb Internal 64gb  NaN              NaN
1244  Hp Oppo A91 Ram 8gb Internal 128gb Second Orig...  NaN              NaN
4702  TECNO Spark 40 Pro Plus | Ram 8gb+256gb | Medi...  NaN              NaN
2407                   Oppo Reno 8 8 256gb second bekas  NaN              NaN
2306  HP OPPO RENO 3 / A91 ram 8gb internal 128gb SE...  NaN              NaN
2771  realme 3 64gb bagus ram 4gb garansi resmi star...  NaN              NaN
5862  Bohancell ‖ Vivo Y71 ram 3gb internal 32gb Sec...  NaN              NaN

In [8]:
phones_df.isna().sum().sort_values(ascending=False)

internal_storage             1201
ram                          1201
brand                           0
release_date                    0
architecture                    0
audio_jack                      0
battery_capacity                0
bluetooth                       0
chipset                         0
cpu                             0
cpu_cores                       0
display_type                    0
edge                            0
expandable_memory               0
face_unlock                     0
features                        0
gprs                            0
title                           0
price                           0
gpu                             0
gps                             0
loudspeaker                     0
height                          0
notch                           0
operating_system                0
os_version                      0
network                         0
pixel_density                   0
primary_camera_resolution       0
quick_charging                  0
ram_type                        0
refresh_rate                    0
resolution                      0
screen_protection               0
screen_size                     0
screen_to_body_ratio            0
sim_size                        0
sim_slot                        0
speed                           0
storage_type                    0
thickness                       0
touch_screen                    0
usb                             0
usb_otg                         0
usb_type_c                      0
video                           0
volte                           0
waterproof                      0
weight                          0
width                           0
wlan                            0
dtype: int64

In [9]:
print("Before Extraction")
print(len(phones_df))

phones_df.dropna(inplace=True)
print("After Extraction")
print(len(phones_df))

Before Extraction
7018
After Extraction
5817

In [10]:
phones_df['release_date'].value_counts()

release_date
03 April 2019        272
25 June 2025         115
15 August 2019       108
10 April 2025         85
31 December 2021      74
                    ...
30 September 2021      1
10 January 2025        1
27 February 2025       1
21 April 2023          1
14 February 2017       1
Name: count, Length: 422, dtype: int64

In [11]:
from datetime import datetime

def reformat_date(str_date):
    date_formats = [
        '%d%B%Y',
        '%d%b%Y',
        '%d,%B,%Y',
        '%d,%b,%Y',
    ]
    
    for format in date_formats:
        try:
            parsed =  datetime.strptime(str_date.replace(" ",""), format)
            return parsed
        except:
            continue

phones_df['release_date'] = phones_df['release_date'].apply(lambda x: reformat_date(x))

phones_df['released_year'] = phones_df['release_date'].dt.year
phones_df['released_month'] = phones_df['release_date'].dt.month
phones_df['released_day'] = phones_df['release_date'].dt.day

In [12]:
phones_df['release_date'].value_counts()

release_date
2019-04-03    272
2025-06-25    115
2019-08-15    108
2025-04-10     85
2021-12-31     74
             ...
2021-09-30      1
2025-01-10      1
2025-02-27      1
2023-04-21      1
2017-02-14      1
Name: count, Length: 420, dtype: int64

In [13]:
phones_df[['release_date','released_day','released_month', 'released_year']]

     release_date  released_day  released_month  released_year
0      2023-07-10          10.0             7.0         2023.0
1      2019-09-15          15.0             9.0         2019.0
2      2022-07-13          13.0             7.0         2022.0
3      2022-09-15          15.0             9.0         2022.0
5      2019-09-15          15.0             9.0         2019.0
...           ...           ...             ...            ...
7008   2023-05-09           9.0             5.0         2023.0
7010   2021-01-18          18.0             1.0         2021.0
7012   2024-10-29          29.0            10.0         2024.0
7013   2020-06-10          10.0             6.0         2020.0
7017   2018-02-14          14.0             2.0         2018.0

[5817 rows x 4 columns]

In [14]:
string_features= phones_df.select_dtypes(include=['object','string'])
string_features.columns

Index(['brand', 'title', 'audio_jack', 'bluetooth', 'chipset', 'cpu',
       'display_type', 'edge', 'expandable_memory', 'face_unlock', 'features',
       'gprs', 'gps', 'gpu', 'internal_storage', 'loudspeaker', 'network',
       'notch', 'operating_system', 'os_version', 'primary_camera_resolution',
       'quick_charging', 'ram', 'ram_type', 'resolution', 'screen_protection',
       'screen_size', 'sim_size', 'sim_slot', 'speed', 'storage_type',
       'touch_screen', 'usb', 'usb_otg', 'usb_type_c', 'video', 'volte',
       'waterproof', 'wlan'],
      dtype='str')

In [15]:
string_features['audio_jack'].unique()

<StringArray>
['3.5mm', 'USBType-C', 'No', '5.3mm']
Length: 4, dtype: str

In [16]:
phones_df.drop(columns=['title', 'release_date'], inplace=True)

In [17]:
len(phones_df)

5817

In [18]:
phones_df.to_csv("datasets/extracted_features_data/phones.csv", index=False)